name: 'doc-check'
description: 'A tool to check if a PR touches code but not the corresponding documentation.'
author: 'FG-TUM'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book'
  color: 'blue'

# Define your inputs here.
inputs:
  githubToken:
    description: 'GitHub token to authenticate the action to interact with the repository.'
    required: true
  # baseBranch:
  #   description: 'The name of the reference branch for comparing changes.'
  #   required: true
  #   default: 'main'
  userDocsDirs:
    description: 'The paths to the directories where the user doc files are, relative to the repository root.'
    required: true
    default: 'docs'

# Define your outputs here.
outputs:
  warnings:
    description: 'All produced warnings.'

runs:
  using: node20
  main: dist/index.js
