name: 'doc-check'
description: 'A tool to check if a PR touches code but not the corresponding documentation.'
author: 'FG-TUM'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book'
  color: 'blue'

# Define your inputs here.
inputs:
  githubToken:
    description: 'GitHub token to authenticate the action to interact with the repository.'
    required: true
  userDocsDirs:
    description: 'The paths to the directories where the user doc files are, relative to the repository root.'
    required: true
    default: 'docs'
  recurseUserDocDirs:
    description: 'Whether to also look for user doc files in all subdirectories of the given directories.'
    required: false
    default: false
  dirTagSectionRegex:
    description: 'The regular expression that is used to identify the section of a documentation file where the tool starts looking for directory tags.'
    required: false
    default: '/Related Files and Folders/i'
  docFileExtensions:
    description: 'File extensions that are considered for doc files.'
    required: false
    default: 'md'
  srcFileExtensions:
    description: 'File extensions that are considered for source files.'
    required: false
    default: 'cpp h txt'

# Define your outputs here.
outputs:
  warnings:
    description: 'All produced warnings.'

runs:
  using: node20
  main: dist/index.js
