name: DocTagChecker

on:
  pull_request

jobs:
  DocTagCheck:
    runs-on: ubuntu-latest
    env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug
        run: |
          echo "-----------------------------------"
          echo $BRANCH_NAME
          echo "-----------------------------------"
          echo ${{ github.head_ref }}
          echo "-----------------------------------"
          echo ${{ github.ref_name }}
          echo "-----------------------------------"
      - name: Check for missing userdoc updates
        # Use the version from the branch that triggered the workflow
        uses: AutoPas/DocTagChecker@${{ github.head_ref || github.ref_name }}
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # multiple paths are separated by whitespace or ','
          userDocsDirs: __tests__/testData/
          # Optional inputs with defaults:
          # DON'T use '/other stuff/i' as it contains intentional fakes
          # dirTagSectionRegex: 
          # Check userDocsDirs recursively.
          recurseUserDocDirs: true
          # File extensions for files to be considered documentation.
          docFileExtensions: md
          # File extensions for files to be considered source code.
          srcFileExtensions: ts
