name: DocTagChecker

on:
  pull_request

jobs:
  DocTagCheck:
    runs-on: ubuntu-latest
    env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    # needed to grant workflows opened by dependabot rights to create comments.
    permissions:
      issues: write
      # actions: write
      # checks: write
      # contents: write
      # deployments: write
      # id-token: write
      # discussions: write
      # packages: write
      # pages: write
      # repository-projects: write
      # security-events: write
      # statuses: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for missing userdoc updates
        # Use the DocTagChecker version from the branch that triggered the workflow
        # This is the repo relative path to actions.yml
        uses: ./
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # multiple paths are separated by whitespace or ','
          userDocsDirs: __tests__/testData/
          # Optional inputs with defaults:
          # DON'T use '/other stuff/i' as it contains intentional fakes
          # dirTagSectionRegex: 
          # Check userDocsDirs recursively.
          recurseUserDocDirs: true
          # File extensions for files to be considered documentation.
          docFileExtensions: md
          # File extensions for files to be considered source code.
          srcFileExtensions: ts
